### ISSUE TITLE
Stops at "Loading accounts"

### ISSUE THREAD

**Issue by Sterioss** [hesa2020/HesaElobuddy#4]
`à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à BananaLib.RestService.LoginQueue.<GetAuthResult>d__68.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à BananaLib.RestService.LoginQueue.<GetAuthToken>d__70.MoveNext()`

**Comment by hesa2020** [comment]
Fixed.
