### ISSUE TITLE
SummonerName Selection - Not Working

### ISSUE THREAD

**Issue by misterblank** [hesa2020/HesaElobuddy#5]
Accounts loaded the first time without a given summoner name do not select a summoner name.

**Comment by misterblank** [comment]
```
Tools.ConsoleMessage(Accountname,"Logging in to your account...", ConsoleColor.White);
loginPacket = await connection.GetLoginDataPacketForUser();
AvailableChampions = await connection.GetAvailableChampions();
if(login... }
```
change it to
```
Tools.ConsoleMessage(Accountname,"Logging in to your account...", ConsoleColor.White);
loginPacket = await connection.GetLoginDataPacketForUser();
if(login... }
AvailableChampions = await connection.GetAvailableChampions();
```
because champion data are not available at the time if you do not have a summoner name. You can close this issue yourself after update. Gratz. PS: Hope the bot will get open source again and you will write me back in skype dude.

**Comment by hesa2020** [comment]
Hey thanks for reporting lol i just noticed you did, and i already changed it :)
